FROM maven:3.9.9 AS build

WORKDIR /app

# Copy the user-service module's pom.xml and source code
COPY auction-service/pom.xml ./auction-service/
COPY auction-service/src ./auction-service/src/

# Download dependencies and build the JAR
RUN mvn -f auction-service/pom.xml clean install -DskipTests

# Step 2: Use OpenJDK to run the application
FROM openjdk:latest

WORKDIR /app

# Copy the built JAR file from the build stage
COPY --from=build /app/auction-service/target/auction-service-0.0.1-SNAPSHOT.jar /app/auction-service.jar

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "auction-service.jar"]