# Step 1: Use Maven to build the project
FROM maven:3.9.9 AS build

WORKDIR /app

# Copy the user-service module's pom.xml and source code
COPY user-service/pom.xml ./user-service/
COPY user-service/src ./user-service/

# Download dependencies and build the JAR
RUN mvn -f user-service/pom.xml clean install -DskipTests

# Step 2: Use OpenJDK to run the application
FROM openjdk:latest

WORKDIR /app

# Copy the built JAR file from the build stage
COPY --from=build /app/user-service/target/user-service-0.0.1-SNAPSHOT.jar /app/user-service.jar

EXPOSE 8083

ENTRYPOINT ["java", "-jar", "user-service.jar"]
